# Flaskex deploy playbook
---
# Используем группу хостов
- hosts: "testhosts"

# Передаем переменную с паролем sudo, используя --ask-vault-pass   
  vars_files:
  - sudopass

# Выполняем все таски с правами суперпользователя  
  become: yes

  tasks:
  - name: "Установка python-pip"
    apt:
      name: "python-pip"
      state: "present"
      update_cache: true

  - name: "Удаление существующей директории"
    file:    
      path: "/opt/flaskex"
      state: "absent"

  - name: "Копирование директории приложения"
    copy:
      src: "/home/devopstst/flaskex"
      dest: "/opt/"
      owner: "devopstst"
      group: "devopstst"
      mode: "0644"

  - name: "Установка необходимых пакетов"
    pip:
      requirements: "/opt/flaskex/requirements.txt"
      state: "present"

  - name: "Удаление существующего скрипта"
    file:
      path: "/opt/scripts/checkrunning.sh"
      state: "absent"

  - name: "Проверка существования директории /opt/scripts"
    file:
       path: "/opt/scripts" 
       state: "directory"
       recurse: yes
       owner: "devopstst"
       group: "devopstst"

  - name: "Копирование скрипта проверки"
    copy:
      src: "/home/devopstst/tstrepo/ansible/checkrunning.sh"
      dest: "/opt/scripts/checkrunning.sh"
      owner: "devopstst"
      group: "devopstst"
      mode: "0755"

  - name: "Запуск приложения, если не запущено"
    shell: "nohup /opt/scripts/checkrunning.sh &"

...
